services:
  - type: web
    name: telegram-bot
    env: node
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false